### PR TITLE
Minor changes. 

### PR DESCRIPTION
**Pull request by Vasikaran**
I have few changes on your project.

### CODE REVIEW

**Comment by philipwalton** [comment]
I'm not sure what the purpose of this PR is, or what problem it's solving. Can you please provide more context?

**Comment by Vasikaran** [comment]
I have three commits on this. 

1. The first one is change export path of your package. I am using node js, I wish to use your package on node js. So I modified export path in package.json file.

2. Second one is changed a line in your firstConsistentlyInteractiveDetector.js file. That line has print a array. But your line looks like 'array ${array}'. This template string pattern converts your array as string. So console output looks like "[object Object]". So I'm converting that by using JSON.stringify method.

3. I need third commit. While yours firstConsistentlyInteractiveDetector.js file running many information printed on console. If you export the collective information its very helpful for me.

That's why I had pull request to you.

**Comment by philipwalton** [comment]
The approach taken here duplicates a lot of code, so instead I just reverted to how it was logged prior to my previous PR. #7 should fix this issue, which has been merged and released in 0.2.2.

Sorry about breaking this yesterday :/

**Comment by Vasikaran** [comment]
Can you give your log reports as output. Now you only give interactive time. If you will give interactive time with log reports, it's very helpful for me.

**Comment by philipwalton** [comment]
Hmmm, I don't see the use-case for that. What do you want to do with the messages besides have them logged to the console?

**Comment by Vasikaran** [comment]
Sorry! I don't need it. But I need to run your API from Node JS. So please change your export path to **src/index.js**.

**Comment by philipwalton** [comment]
If you want to import the ES2015 source directly from node you can run `require('tti-polyfill/src')`. That's [what I do on my site](https://github.com/philipwalton/blog/blob/master/assets/javascript/analytics.js#L9).

**Comment by Vasikaran** [comment]
Thanks! @philipwalton. I want this.

**Pull request closed without merging**
